# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 301, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.manualButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.manualButton.setMinimumSize(QtCore.QSize(0, 100))
        self.manualButton.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.manualButton.setFont(font)
        self.manualButton.setObjectName("manualButton")
        self.verticalLayout.addWidget(self.manualButton)
        self.fileButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.fileButton.setMinimumSize(QtCore.QSize(0, 100))
        self.fileButton.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.fileButton.setFont(font)
        self.fileButton.setObjectName("fileButton")
        self.verticalLayout.addWidget(self.fileButton)
        self.randomButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.randomButton.setMinimumSize(QtCore.QSize(100, 100))
        self.randomButton.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.randomButton.setFont(font)
        self.randomButton.setObjectName("randomButton")
        self.verticalLayout.addWidget(self.randomButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.manualButton.setText(_translate("MainWindow", "Manual"))
        self.fileButton.setText(_translate("MainWindow", "File"))
        self.randomButton.setText(_translate("MainWindow", "Random"))
        self.label.setText(_translate("MainWindow", "Setup"))
